# Docker Compose NERVE instance (Tomcat + OpenJDK + NERVE)
# * saves logs in a volume

version: '3'

services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NERVE_NERSCRIBER_SRC=/mnt/NERVE/NERScriber
        - NERVE_NERSCRIBER_TARGET=/mnt/NERVE/NERScriber/target
    ports:
      - 6642:8080
      - 6643:8009
    volumes:
      - ./container_volumes/tomcat_logs/:/usr/local/tomcat/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
