# Docker Compose NERVE instance (Tomcat + OpenJDK + NERVE)
# * for testing Dockerfile

version: '3'

services:

  webapp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6644:8080
      - 6645:8009
    volumes:
      - ./container_volumes/tomcat_logs-dev/:/usr/local/tomcat/logs
    environment:
      - LOG_LEVEL=VERBOSE # Log4J Logging level: TRACE, WARN, VERBOSE
    restart: unless-stopped
    stdin_open: true
    tty: true
